#*************************************************************************
# Copyright (c) 2002 The University of Chicago, as Operator of Argonne
# National Laboratory.
# Copyright (c) 2002 The Regents of the University of California, as
# Operator of Los Alamos National Laboratory.
# This file is distributed subject to a Software License Agreement found
# in the file LICENSE that is included with this distribution. 
#*************************************************************************
#
# $Id: Makefile,v 1.3 2003-07-24 15:12:54 soliday Exp $
#
TOP = ../..

include $(TOP)/configure/CONFIG

CMPLR=ANSI
HDEPENDS_FILES =

USR_CFLAGS += 	-I$(EPICS_BASE)/include -I$(EPICS_BASE)/include/os/$(OS_CLASS) \
		-DACCESS_SECURITY -D_NO_PROTO -I$(EPICS_EXTENSIONS)/src/SDDS/lzma
USR_CXXFLAGS += -I$(EPICS_BASE)/include -I$(EPICS_BASE)/include/os/$(OS_CLASS) \
		-DACCESS_SECURITY -D_NO_PROTO -I$(EPICS_EXTENSIONS)/src/SDDS/lzma
USR_CXXFLAGS_DEFAULT += -fpermissive
USR_CXXFLAGS_WIN32 += -permissive
USR_LDFLAGS_Linux += -fopenmp

ifeq ($(EPICS_VERSION),3)
cavput_SRCS = cavput.cc pvMultList.c
cavget_SRCS = cavget.cc pvMultList.c
cawait_SRCS = cawait.cc
else
cavput_SRCS = cavput.cc pvMultList.c pvaSDDS.cc
cavget_SRCS = cavget.cc pvMultList.c pvaSDDS.cc
cawait_SRCS = cawait.cc pvaSDDS.cc
endif

ifeq ($(EPICS_VERSION).$(EPICS_REVISION),3.13)
PROD = cavput cawait cavget
else
PROD_HOST = cavput cawait cavget
endif



GSL = $(words $(wildcard ../../SDDS/gsl))
ifeq ($(GSL), 1)
GSLLIB = gsl gslcblas
SYS_GSLLIB = 
else
#Look for system version of GSL
SYSGSL = $(words $(notdir $(wildcard \
/usr/lib/libgsl.a \
/usr/lib/libgsl.so \
/usr/lib64/libgsl.a \
/usr/lib64/libgsl.so \
/usr/lib/i386-linux-gnu/libgsl.so \
/usr/lib/i386-linux-gnu/libgsl.a \
/usr/lib/x86_64-linux-gnu/libgsl.so \
/usr/lib/x86_64-linux-gnu/libgsl.a \
/lib/i386-linux-gnu/libgsl.so \
/lib/i386-linux-gnu/libgsl.a \
/lib/x86_64-linux-gnu/libgsl.so \
/lib/x86_64-linux-gnu/libgsl.a \
/lib/libgsl.a \
/lib/libgsl.so \
/lib64/libgsl.a \
/lib64/libgsl.so \
/sw/lib/libgsl.a \
/sw/lib/libgsl.dylib \
/opt/local/lib/libgsl.a \
/opt/local/lib/libgsl.dylib \
/usr/sfw/lib/libgsl.a \
/usr/sfw/lib/libgsl.so )))
ifneq ($(SYSGSL), 0)
GSLLIB = 
SYS_GSLLIB = gsl gslcblas
else
#No GSL library found. Build without it.
GSLLIB = 
SYS_GSLLIB = 
endif
endif


PROD_LIBS = mdbcommon matlib fftpack SDDS1 rpnlib mdbmth mdblib lzma $(GSLLIB) ca Com


PROD_LIBS_WIN32 += z
PROD_LIBS_BORLAND += z
SYS_PROD_LIBS_DEFAULT += z $(SYS_GSLLIB)
SYS_PROD_LIBS_solaris += z posix4
SYS_PROD_LIBS_WIN32 = ws2_32
SYS_PROD_LIBS_BORLAND = -nil-

ifeq ($(EPICS_VERSION),7)
cavget_LIBS += pvaClient nt pvAccessCA pvAccess pvData
cavput_LIBS += pvaClient nt pvAccessCA pvAccess pvData
cawait_LIBS += pvaClient nt pvAccessCA pvAccess pvData
endif

ifeq ($(HOST_ARCH),solaris)
ACC_DEP_CFLAGS = -KPIC -v
CCC_DEP_CFLAGS = -KPIC -v
GCC_DEP_CFLAGS += -D__EXTENSIONS__
endif

SDDS1_DIR = $(INSTALL_LIB)
mdblib_DIR = $(INSTALL_LIB)
mdbmth_DIR = $(INSTALL_LIB)
matlib_DIR = $(INSTALL_LIB)
fftpack_DIR = $(INSTALL_LIB)
rpnlib_DIR = $(INSTALL_LIB)
mdbcommon_DIR = $(INSTALL_LIB)
z_DIR = $(INSTALL_LIB)
lzma_DIR = $(INSTALL_LIB)


include $(TOP)/configure/RULES
